[workspace]
channels = ["robostack-jazzy", "conda-forge"]
name = "egb320"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]
build = "colcon build --symlink-install"

[dependencies]
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-turtlesim = ">=1.8.3,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
pkg-config = ">=0.29.2,<0.30"

[pypi-dependencies]
pyfakewebcam = ">=0.1.0, <0.2"
opencv-python = "*"
gpiozero = ">=2.0.1, <3"
lgpio = ">=0.2.2.0, <0.3"
