[workspace]
channels = ["robostack-jazzy", "conda-forge"]
name = "egb320"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]
build = "colcon build --symlink-install"
bridge = "ros2 launch rosbridge_server rosbridge_websocket_launch.xml"
vision = "ros2 run robot vision"
navigation = "ros2 run robot navigation"
collection  = "ros2 run robot collection"
mobility = "ros2 run robot mobility"
test = "ros2 run robot test"
pid = "ros2 run robot pid"

[activation]
scripts = ["install/setup.sh"]

[dependencies]
ros-jazzy-ros-base = ">=0.11.0,<0.12"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
pkg-config = ">=0.29.2,<0.30"
ros-jazzy-rosbridge-suite = ">=2.1.0,<3"
scipy = ">=1.16.2,<2"

[pypi-dependencies]
lgpio = ">=0.2.2.0, <0.3"
gpiozero = ">=2.0.1, <3"
pyfakewebcam = ">=0.1.0, <0.2"
opencv-python = "*"
smbus = ">=1.1.post2, <2"
piicodev = ">=1.10.3, <2"
rpi-hardware-pwm = ">=0.3.0, <0.4"
